### ISSUE TITLE
Stuck loading at 60%

### ISSUE THREAD

**Issue by QuickRick101** [Percedal/FS22_UpgradableFactories#16]
I have the latest update that was supposed to fix save game loadingstuck at 99%. This seems to be a capatability issue with the pumps and hoses dlc with the bio gas plants. I was able to get it to work once but i had to set all my materials fill level to 0 from the biogas plant in the game save in order for it to load properly. Then once in the game i couldnt purchase the materials from the productions menu. I run many mods including production revamp i have all the dlc from giants so it may also be another mod interfereing with this as well. The game gets stuck either at 60% or at 80% mostly its at 60% disabling the mod allows it to load normally.

**Comment by Percedal** [comment]
Yes, for right now the mod is not compatible with PnH DLC. I'm working on this.

**Comment by Iwan1803** [comment]
Tried latest beta version 1.2.0.0 and still got stuck at 60% loading:
`2023-01-02 09:14   UpgradableFactories: Loading XML...
2023-01-02 09:14   UpgradableFactories: 37 productions loaded from XML
2023-01-02 09:14   UpgradableFactories: Production maximum level: 10
2023-01-02 09:14 Error: Running LUA method 'loadSharedI3DFileFinished'.
D:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_UpgradableFactories/UpgradableFactories.lua:305: attempt to compare number with nil`
Screenshot from the upgradableFactories.xml:
![image](https://user-images.githubusercontent.com/47528836/210207623-fe534ced-0afe-46ae-af84-e7100a83c056.png)
These entries should be the generators from PnH-DLC:
![image](https://user-images.githubusercontent.com/47528836/210208361-e1d413a8-0165-41fc-bc26-6fb8cf8d0498.png)
If i delete the entries from id 32 to 37, the savegame can be loaded.

**Comment by Iwan1803** [comment]
I deleted the entries from id 32 to 37, downloaded the version which was released 13 hours ago and after saving and loading the savegame it works.
BUT now some productions are gone which where upgraded to level 2 before and some others are missing.
The old file contained this productions:
![image](https://user-images.githubusercontent.com/47528836/210956334-e5ba9940-9056-4483-84fc-1ebe2e8a7e5b.png)
In the new file a lot are gone:
![image](https://user-images.githubusercontent.com/47528836/210957356-0e94859d-a449-4e0c-8aaf-6f10ada7c613.png)
The IDs from 2 to 4 are now empty and 15 to 31 are gone. That all BGA entries are gone, is ok for me, but some of the productions are also gone.
Nothing was written in the log. Maybe you can add a debug so that there will be an info in the log why a production was not added.

**Comment by Percedal** [comment]
Thank you for your feeback on the lastest pre-release. For this I really need the log file, it already contains some debug info

**Comment by Iwan1803** [comment]
Maybe i need more coffee but i didn't saw anything in the log.

**Comment by Percedal** [comment]
I published a updated version that, i hope, will help us troubleshoot the pb. direct download [here](https://github.com/Percedal/FS22_UpgradableFactories/releases/download/v1.2.0.0/FS22_UpgradableFactories.zip)

**Comment by Percedal** [comment]
I found the issue, basically when loading the xml the tag `<production/>` cause the loading procedure to halt (so what comes after is not read). The empty tags were produced by the save function and it's now fixed.
The v1.2.0.0 pre-release will be updated in consequence.

**Comment by Iwan1803** [comment]
Looks good!

**Comment by Percedal** [comment]
I like to hear that!
