### ISSUE TITLE
Patch 1.13.1 error

### ISSUE THREAD

**Issue by Knowen** [Percedal/FS22_UpgradableFactories#46]
Hello @Percedal,

with the latest patch 1.13.1 i get this error in my log file which semi-freeze my game:
`dataS/scripts/objects/Storage.lua(362) : attempt to perform arithmetic on local 'fillLevel' (a nil value)`

If i deactivate this mod, my save file loads without any issues and i can play.

**Comment by Shad0wlife** [comment]
I could not reproduce that yet. What is the situation you have? Loading a game with upgraded factories in them? Because I have tested with multiple updated sawmills with and without "production revamp" installed and did not get that error.
My best guess here is, that the vanilla code that threw the error you have asynchronously executed while the mod code replaced the full fillLevels structure of the Storage, making the single fillLevel that was operated on invalid... But if that is actually the case, that'll be kinda hard to reproduce and analyze though.

**Comment by Knowen** [comment]
In my save file, I have several upgraded revamp factories. And as written everything works and loads fine as long as this mod is disabled. If it's activated I get this error message.

Of course, if I deactivate the production mod (which I updated) and have upgradable factories activated, the game loads also without any issue.

**Comment by Knowen** [comment]
As the error says something with storage.lua I deactivated step by step all mods that somehow interact with storage. Display panels, time-saving stock check and so on..and I kept UpgradableFactories activated. I still got the error every time. 

Only way to load without the error is to deactivate UpgradableFactories..

**Comment by Shad0wlife** [comment]
Thanks for the effort, that is really good to know. About how many factories would you say you have? And are many of those modded or are most of them base game?

**Comment by Knowen** [comment]
Around 8 or 9 factories and all are from _FED Action_: [https://forbidden-mods.de/filebase/file/30225-fed-produktions-pack/](url)

**Comment by Shad0wlife** [comment]
Ah I have only used the map, not the productions yet. If I find the time I'll try to check them out. Maybe they have custom lua code that could cause the conflict.

**Comment by Knowen** [comment]
Okay, I found the error. It was the Pumps n Hoses DLC. This DLC is not yet ready for 1.13.1 and causes the issue. If I deactivate this DLC the game loads even with UpgradableFactories on. So the problem is solved.
