### ISSUE TITLE
Causes loading error

### ISSUE THREAD

**Issue by Testing123-svg** [Percedal/FS22_UpgradableFactories#9]
Error from log

FS22_UpgradableFactories/UpgradableFactories.lua:131: attempt to index a nil value

**Comment by Percedal** [comment]
please join the log file and how that happened? was it the first load of the mod? new save? everything that can help me investigate it

**Comment by Testing123-svg** [comment]
2nd load. I don't have that log or save anymore. I checked out the method. Not too familiar with lua and modding FS22 but it should solve the error if you check variables for nil values and return if nil in that method.

**Comment by unwisegeek** [comment]
Found it in my log. The error is on line 134 in UpgradableFactories.lua.

**Comment by unwisegeek** [comment]
I'm able to replicate this. Here's how I do it:

1. Have Paint and Terraform Anywhere mod
2. Place a production point on land I do not own, so it gets automatically set to owned by Farm 15
3. Set ownership of the production point from Farm 15 to Farm 1 
4. Save
5. Restart the game and see the error
6. Force the game to exit
7. Remove the production point from upgradeableFactories.xml
8. Game starts normally

The placeable exists in upgradableFactories.xml, but since it's not an actual placeable owned by farm 1, it returns a bad value with the productionPoints method on line 134. Not sure why on that. Probably because it's called only on FarmIds[1] and the production point is associated with FarmIds[15]?

I hope this helps!

**Comment by Percedal** [comment]
I found a the bug for `UpgradableFactories.lua:131: attempt to index a nil value` caused when loading the game and upgradeableFactories.xml has no productions registered, this should be fixed in the next patch.
But I will check anyway to replicate the bug as suggested.

**Comment by Percedal** [comment]
> 2. Place a production point on land I do not own, so it gets automatically set to owned by Farm 15
That's a strange behaviour. When I tried with only the 2 mods (UF and Place&Terraform), a production placed on a non-owned land is assign to farmId 1. Tested on solo and Elmcreek, no farmId 15 to be found. At this point I really dont know what is appening here.

> The placeable exists in upgradableFactories.xml, but since it's not an actual placeable owned by farm 1, it returns a bad value with the productionPoints method on line 134. Not sure why on that. Probably because it's called only on FarmIds[1] and the production point is associated with FarmIds[15]?
Yes obviously. In vanilla solo player only farmId 1 exist for the player (there is also id 0 for NPC but that out of this scope) so if somehow the production you placed is assign to another farmId it will be problematic. If you have any id what can cause this behaviour that would help me troubleshout what's going on.

**Comment by unwisegeek** [comment]
I've seen it with some maps where the BGA is on land that isn't owned by the player, so it gets assigned to FarmId 15 until the production point is bought. The BGA on Griffin Indiana for an example.

Writing this got me thinking, and I tested with the base-game BGAs with all mods unloaded. With Place & Terraform, they're assigned to FarmId 15. Unrelated, but I also found that placing a placable on land you don't own causes it to not show any of the interaction points, but that's a bug for the Place&Terraform Everywhere dev.

Can you take a look at the interaction between your mod and BGAs?

**Comment by Percedal** [comment]
ok so I agree with you on Griffin Indiana, I found the prod with farmId 15 which is linked to a ownable farmland, now it makes more sense. But I didn't see any error message or whatsoever, probably because I tested with latest pre-release version 1.1.0.0. I will further study it but nor for now.
If you feel it, can you download v1.1.0.0 to see if the problem still exists? Be cautious, backup you files. It should'nt mess everything but better safe than sorry...
I'm closing this issue because the original bug is solved. If you test and the bug you mentionned persists, open a new issue. Thanks for help.
